name: "Release"
on:
  push:
    paths:
      - dist/**
    branches:
      - master

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: NPM install
        run: npm ci
      - name: Release 🎉
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
