name: "Tests"
on:
  pull_request:
  push:
    paths-ignore:
      - dist/**
    branches:
      - master

jobs:
  Test-stable:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: NPM Install
      run: npm ci
    - name: Build
      run: npm run build
    - uses: ./
    - name: Get Atom versions
      run: atom -v
    - name: Get APM versions
      run: apm -v

  Test-beta:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: NPM Install
      run: npm ci
    - name: Build
      run: npm run build
    - uses: ./
      with:
        channel: beta
    - name: Get Atom versions
      run: atom -v
    - name: Get APM versions
      run: apm -v

  Lint:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: NPM install
        run: npm ci
      - name: Lint ✨
        run: npm run lint

  Build:
    needs: [Test-stable, Test-beta, Lint]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: NPM install
        run: npm ci
      - name: Build 🧱
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm run build
          if ! git diff --quiet -- dist ; then
            git config user.email "actions@example.com"
            git config user.name "Actions"
            git config credential.helper "store --file=.git/credentials"
            echo "https://${GH_TOKEN}:@github.com" > .git/credentials
            git commit -m 'chore(build): 🧱 build' -- dist
            git push origin HEAD:master
          fi

  Skip:
    if: contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - name: Skip CI 🚫
        run: echo skip ci
