name: "test-local"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  linux-stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
    - name: Get Atom versions
      run: atom -v
    - name: Get APM versions
      run: apm -v

  linux-beta:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        channel: 'beta'
    - name: Get Atom-beta versions
      run: atom-beta -v
    - name: Get APM versions
      run: apm -v
    - name: Get APM-beta versions
      run: apm-beta -v
    - name: Get Atom versions
      run: atom -v

  macos-stable:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
    - name: Get Atom versions
      run: atom -v
    - name: Get APM versions
      run: apm -v

  macos-beta:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        channel: 'beta'
    - name: Get Atom versions
      run: atom -v
    - name: Get APM versions
      run: apm -v

  windows-stable:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
    - name: Get Atom versions
      run: atom -v
    - name: Get APM versions
      run: apm -v

  windows-beta:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        channel: 'beta'
    - name: Get Atom versions
      run: atom -v
    - name: Get APM versions
      run: apm -v
