name: "CI"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Test-stable:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: NPM Install
      run: npm ci
    - name: Build
      run: npm run build
    - uses: ./
    - name: Get Atom versions
      run: atom -v
    - name: Get APM versions
      run: apm -v

  Test-beta:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: NPM Install
      run: npm ci
    - name: Build
      run: npm run build
    - uses: ./
      with:
        channel: beta
    - name: Get Atom versions
      run: atom -v
    - name: Get APM versions
      run: apm -v

  Lint:
    needs: [Test-stable, Test-beta]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: NPM install
        run: npm ci
      - name: Lint ✨
        run: npm run lint

  Build:
    needs: [Lint]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: NPM install
        run: npm ci
      - name: Build 🧱
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm run build
          if ! git diff --quiet -- dist ; then
            git commit -m '🧱 build [skip ci]' -- dist
            git push "https://${GITHUB_ACTOR}:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:master
          fi

  Release:
    needs: [Build]
    if: startsWith(github.repository, 'UziTech/') &&
      github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Release 🎉
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release

  Skip:
    if: contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - name: Skip CI 🚫
        run: echo skip ci
