name: "CI"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Check-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: NPM install
        run: npm ci
      - name: Check build
        run: npm run check-build

  Test-stable:
    needs: [Check-build]
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: ./
    - name: Get Atom versions
      run: atom -v
    - name: Get APM versions
      run: apm -v

  Test-beta:
    needs: [Check-build]
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        channel: beta
    - name: Get Atom versions
      run: atom -v
    - name: Get APM versions
      run: apm -v

  Lint:
    needs: [Test-stable, Test-beta]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: NPM install
        run: npm ci
      - name: Lint ✨
        run: npm run lint

  Release:
    needs: [Lint]
    if: startsWith(github.repository, 'UziTech/') &&
      github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: NPM install
        run: npm ci
      - name: Release 🎉
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run semantic-release

  Skip:
    if: contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - name: Skip CI 🚫
        run: echo skip ci
